import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'app';
  body = 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt sequi deserunt repellat ratione esse eligendi quia! At, nisi eos consectetur deleniti consequatur laborum? Sequi amet, corrupti a dolores, placeat explicabo quis cum sit sint nobis nostrum modi assumenda? Rerum atque pariatur aliquam quibusdam iste dolores alias labore harum? Iusto asperiores reprehenderit doloribus rerum dolorem reiciendis, fugiat eligendi placeat aspernatur iure veniam error quos distinctio quisquam omnis molestias laboriosam. Blanditiis, modi? Voluptates modi dolorem sit inventore dolorum, dolores quod. Excepturi corporis quod a cumque beatae facere fuga quisquam iusto exercitationem laboriosam consequuntur dicta, reprehenderit fugit et, veniam dolor omnis temporibus nulla, asperiores accusamus minus labore commodi repellat! Numquam at suscipit rerum expedita totam iste dolorem incidunt deleniti amet veniam minus quis quo sunt tenetur neque, sint exercitationem, voluptatem enim tempora est magnam ipsum, similique harum fugiat! Placeat porro, molestiae quae voluptatum et incidunt a qui tenetur necessitatibus illum ratione labore cumque accusantium. Ducimus dolorum veritatis quam perspiciatis consequuntur culpa at saepe placeat? Repudiandae mollitia quaerat magni animi asperiores dolorem blanditiis, sapiente nihil veniam! Ad praesentium rerum dolor vero, voluptatibus sapiente facere rem vitae impedit assumenda! Nisi enim voluptatum odit optio facilis assumenda, necessitatibus tenetur temporibus quidem ducimus. Incidunt dolor saepe iste neque maiores magni recusandae voluptatibus qui illo labore ipsum reprehenderit excepturi perferendis voluptatum velit ab ad, officiis pariatur ex perspiciatis, dolorum quia fuga aliquid. Nihil harum ex doloribus quod, nisi debitis porro officiis soluta sit dignissimos architecto fuga ea saepe modi impedit enim omnis fugit provident quas deleniti aspernatur? Fugit facilis perspiciatis id quos illum quis, facere nihil rerum, quo reiciendis, libero doloribus dolores iusto. Sed iusto, maiores aut, ullam architecto sint ipsam commodi ipsum aliquam explicabo itaque voluptatibus ad autem temporibus! Obcaecati culpa, eius perferendis enim dolorem est repudiandae nobis, doloribus accusantium ad reprehenderit illo, sequi quod voluptas illum!'
}
